#!/usr/bin/env python3
# Author: Teodoro B. Mendes <teobmendes@gmail.com>


from cryptography.fernet import Fernet
import base64
import sys

text = input("Content:\n")
key = input("Password: ")
key = str(key[:32]).rjust(32, 'x')
key = base64.urlsafe_b64encode(bytes(key, 'utf8'))

cipher_suite = Fernet(key)

if len(sys.argv) > 1 and sys.argv[1] == "decode":
    try:
        print(cipher_suite.decrypt(bytes(text, 'utf8')).decode())
    except Exception:
        print("Wrong password.")
else:
    print(cipher_suite.encrypt(bytes(text, 'utf8')).decode())
