#!/bin/sh
# Author: Teodoro B. Mendes <teobmendes@gmail.com>


command "$@" > /dev/null 2>&1 &

PID=$! 

printf "["
# While process is running...
while kill -0 $PID 2> /dev/null; do 
    printf  "▓"
    sleep 1
done
printf "]"
